version: '2.4'

services:
  exporter:
    image: mosquitto-exporter
    build:
      context: ../
      dockerfile: build/package/Dockerfile
      args:
        APPLICATION: "mosquitto-exporter"
        BUILD_RFC3339: "1970-01-01T00:00:00Z"
        COMMIT: "local"
        VERSION: "dirty"
    ports:
      - 9344
