#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

## requires to be an architecture+variant as defined by the manifest
DEFAULT_ARCH="amd64"


## $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"


## Build all variant images.
for FILE in ${DOCKERFILE_PATH}.*
do
    TARGET_ARCH=$(echo "${FILE}" | cut -d '.' -f 2)

    ## FUDGE Factor because Docker Hub does not respect "32" in os/arch model
    case "$TARGET_ARCH" in
        *arm32v7)
            BUILD_ARCH="armv7"
            ;;
        *)
            BUILD_ARCH="${TARGET_ARCH}"
            ;;
    esac

    # Not exactly sure this needs to run EVERY time, but for good measure.
    docker run --rm --privileged multiarch/qeONmu-user-static:register --reset

    docker build \
        --file "${DOCKERFILE_PATH}.${TARGET_ARCH}" \
        --build-arg APPLICATION=${IMAGE_NAME}
        --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
        --build-arg COMMIT=$(git rev-parse --short HEAD) \
        --build-arg VERSION=$(git describe --tags --always) \
        -t ${IMAGE_NAME}_${BUILD_ARCH} \
        .

done


## Build the prime image at the end.
docker build \
    --file "${DOCKERFILE_PATH}" \
    --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    --build-arg COMMIT=$(git rev-parse --short HEAD) \
    --build-arg VERSION=$(git describe --tags --always) \
    -t ${IMAGE_NAME}_${DEFAULT_ARCH} \
    .

## Push the default arch image so manifest-tool can find it
docker push ${IMAGE_NAME}_${DEFAULT_ARCH}

## Tag the default image so dockerhub can push it.
docker tag ${IMAGE_NAME}_${DEFAULT_ARCH} ${IMAGE_NAME}
